name: Build and deploy Android Release
on:
  push:
    tags:
      - 'android-release-*'
    branches:
      - 'ci/android-release-*'
      - ci/universal-release-*
  workflow_dispatch:
    inputs:
      buildchannel:
        description: 'Build Channel'
        required: true
        default: 'selfhost'
        type: choice
        options:
          - selfhost
          - selfhost-reg
      REALLY_UPLOAD:
        required: true
        type: boolean
        default: true
  workflow_call:
    secrets:
      RABBY_MOBILE_ANDROID_KEY_STORE:
        required: false
      RABBY_MOBILE_ANDROID_STORE_PASSWORD:
        required: false
      RABBY_MOBILE_ANDROID_KEY_PASSWORD:
        required: false
      RABBY_MOBILE_ANDROID_KEY_ALIAS:
        required: false
      RABBY_MOBILE_KR_PWD:
        required: false

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}
env:
  BUILD_TARGET_PLATFORM: android

concurrency:
  group: android-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-build:
    name: android-release-build
    environment: Production
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      RABBY_MOBILE_NM_USE_CACHE: 'true'
      RABBY_MOBILE_METRO_NODE_MAX_OLD_SPACE_SIZE: '3072'
      RABBY_MOBILE_METRO_MAX_WORKERS: '4'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          clean: false

      - name: Clean git Manually
        run: |
          yarn_exclude_args=()
          if [ "$RABBY_MOBILE_NM_USE_CACHE" = "true" ]; then
            echo "Keep yarn install outputs";
            yarn_exclude_args+=(
              -e node_modules
              -e 'apps/*/node_modules'
              -e 'packages/*/node_modules'
              -e .yarn/install-state.gz
              -e .yarn/unplugged
            )
          fi

          git clean -ffdx "${yarn_exclude_args[@]}";
          git reset --hard HEAD;

      - name: Get Actions Variables
        id: actionvars
        run: |
          trigger_date=$(date +'%Y%m%d%H%M%S')
          echo "trigger_date=$trigger_date" >> "$GITHUB_OUTPUT"

          flatten_refname=${GITHUB_REF_NAME//\//'_'}
          flatten_refname=${flatten_refname//\./'_'}
          echo "flatten_refname=$flatten_refname" >> "$GITHUB_OUTPUT"

      - name: '[Android] Setup Nodejs and Yarn'
        if: runner.os == 'Linux'
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Java
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc # v2

      - name: Install & Build app
        run: |
          cd apps/mobile;
          RABBY_MOBILE_RUN_POSTINSTALL=true bash ./scripts/ci/prepare-mobile-build.sh;

          [ -z "$buildchannel" ] && export buildchannel=selfhost;
          [ -z "${REALLY_UPLOAD:-}" ] && export REALLY_UPLOAD=true;
          bash ./scripts/deploy-android.sh
        env:
          FLATTEN_REFNAME: ${{ steps.actionvars.outputs.flatten_refname }}
          TRIGGER_DATE: ${{ steps.actionvars.outputs.trigger_date }}
          RABBY_MOBILE_BUILD_BUCKET: ${{ secrets.RABBY_MOBILE_BUILD_BUCKET }}
          RABBY_MOBILE_KR_PWD: ${{ secrets.RABBY_MOBILE_KR_PWD }}
          RABBY_MOBILE_CODE: ${{ secrets.RABBY_MOBILE_CODE2 }}
          RABBY_MOBILE_ANDROID_KEY_STORE: ${{ secrets.RABBY_MOBILE_ANDROID_KEY_STORE }}
          RABBY_MOBILE_ANDROID_STORE_PASSWORD: ${{ secrets.RABBY_MOBILE_ANDROID_STORE_PASSWORD }}
          RABBY_MOBILE_ANDROID_KEY_PASSWORD: ${{ secrets.RABBY_MOBILE_ANDROID_KEY_PASSWORD }}
          RABBY_MOBILE_ANDROID_KEY_ALIAS: ${{ secrets.RABBY_MOBILE_ANDROID_KEY_ALIAS }}
          RABBY_MOBILE_SENTRY_AUTH_TOKEN2: ${{ secrets.RABBY_MOBILE_SENTRY_AUTH_TOKEN2 }}
          SENTRY_AUTH_TOKEN: ${{ secrets.RABBY_MOBILE_SENTRY_AUTH_TOKEN2 }}
          RABBY_MOBILE_LARK_CHAT_URL: ${{ secrets.LARK_CHAT_URL }}
          RABBY_MOBILE_LARK_CHAT_SECRET: ${{ secrets.LARK_CHAT_SECRET }}
          RABBY_ROBOT_LARK_APP_ID: ${{ secrets.RABBY_ROBOT_LARK_APP_ID }}
          RABBY_ROBOT_LARK_APP_SECRET: ${{ secrets.RABBY_ROBOT_LARK_APP_SECRET }}
          buildchannel: ${{ inputs.buildchannel }}
          REALLY_UPLOAD: ${{ inputs.REALLY_UPLOAD }}
          # see more details on https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          GIT_ACTIONS_JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
          GIT_COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          GIT_REF_NAME: ${{ github.ref_name }}
          GIT_REF_URL: ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}
          GITHUB_REF: ${{ github.ref }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rabbymobile-${{ steps.actionvars.outputs.flatten_refname }}-${{ steps.actionvars.outputs.trigger_date }}
          path: |
              ./apps/mobile/android/app/build/outputs/apk/release/app-release.apk
